name: discovery_env
channels:
  - apple
  - pytorch
  - defaults
dependencies:
  - python=3.10.9
  - pytorch=2.0.0
  - torchvision=0.15
  # Installing using conda avoids recent pip install issues
  - grpcio=1.48.2
  - pip=23.1.2
  - pip:
      # opensearch
      - opensearch-py==2.3.2
      - jsonpath-ng==1.6.0

      # AWS
      - awswrangler==3.7.1
      - sagemaker==2.237.1

      # # ML Frameworks
      - tensorflow==2.14.1
      - tensorflow-metal==1.1.0
      - tensorflow-io==0.37.1
      - scikit-learn==1.5.2

      # ML Libs
      - transformers==4.47.1
      - sentence-transformers==2.2.2
      - faiss-cpu==1.7.4 # Vector indexes
      - wandb==0.19.1

      # Model Hubs
      - tensorflow_hub==0.16.1
      - huggingface-hub==0.27.1
      - keras-hub==0.16.1

      # Datasets packages
      - datasets==2.14.5

      # Environemt
      - dynaconf==3.2.4
      - tenacity==8.2.2
      - grpcio-tools==1.48.2
      - grpcio-health-checking==1.48.2
      - srsly==2.4.6

      # Pre commit hooks
      - pre-commit==4.0.1
      - autoflake==2.3.1
      - black==24.10.0
      - isort==5.13.2
      - mypy==1.14.1
      - nbqa[toolchain]==1.9.1

      # Lambda Deployment packages
      - aws-cdk-lib>=2.0.0
      - constructs>=10.0.0

      # Statsig for feature flags
      - statsig==0.17.1

      # --------------------------------------------------------
      # Dev packages
      # --------------------------------------------------------
      - jupyterlab==3.6.1
      - matplotlib==3.7.0
      - ipywidgets==8.0.4
      - gradio==5.1.0
      - plotly==5.19.0

      # For issues related to VSCode editor jupyter-client & pyzmq
      - jupyter-client==7.4.9
      - pyzmq==24.0.1

      # Testing packages
      - pytest==7.2.2
      # Removing version because sagemaker package is not compatible with mock==5.0.1
      - mock
      - types-mock

      # Misc
      - requests==2.32.3
      - types-requests==2.32.0.20241016
